### PR TITLE
Replace all stempy-jupyterlab with stempy-ipykernel

### LINKED ISSUE #1193: Update Jupyter notebooks default kernel name
The kernel name has changed from `stempy-jupyterlab` to `stempy-ipykernel`. Please update the templates to use the new kernel name. 

For example [this line](https://github.com/OpenChemistry/distiller/blob/2d0c0dd2c187dd55fd7b9ada2958a9a0d01fac90/backend/faust/templates/vacuum_scan_prepare.ipynb.j2#L334) is now incorrect.

### PR DESCRIPTION
**Pull request by swelborn**
fixes #1193

### CODE REVIEW

**Comment by swelborn** [comment]
notebook worker has been updated in prod and will test when pm is back up

**Comment by swelborn** [comment]
New notebooks are now generated with the following in the metadata

```
display_name:"stempy-ipykernel"
language:"python"
name:"stempy-ipykernel"
```

I don't have this exact kernel name installed in my home dir. Let me know if you see any problems @ercius, otherwise we can close this.

**Comment by ercius** [comment]
Looks good to me. You can install this kernel using this script:
`/global/cfs/cdirs/ncemhub/kernels/stempy_ipykernel_kernel.sh`

**Comment by ercius** [comment]
I think this is now working and can be merged.

**Pull request merged**
