### PR TITLE
Improve meta data in scan page

### LINKED ISSUE #711: Improve meta data in scan page
The DM4 file has a lot of extraneous meta data that is currently added to the Advanced information in each scan page. 

1) We should rename this to Metadata.
2) I wrote a filter which captures most of the wanted tags:
```python
metadata = {}
good_keys = ['Calibrations', 'Acquisition', 'DataBar', 'EELS', 'Meta Data', 'Microscope Info', 'Session Info', '4Dcamera', 'DigiScan']
for kk, ii in f0.allTags.items():
    if any(x in kk for x in good_keys):
        kk_split = kk.split('.')
        if 'DigiScan' in kk:
            if 'Rotation' in kk:
                new_key = ' '.join(kk_split[4:])
                metadata[new_key] = ii
        elif 'Session Info' in kk:
            if 'Label' in kk_split[-1]:
                label = ii
            if 'Value' in kk_split[-1]:
                value = ii
                metadata[label] = value
        else:
            new_key = ' '.join(kk_split[4:])
            metadata[new_key] = ii
            
for k,v in metadata.items():
    print('{} = {}'.format(k,v))
```

Please let me know the preferred way to write this filter. Im not sure how Distiller extracts this information.

### PR DESCRIPTION
**Pull request by alesgenova**
Fixes #711

### CODE REVIEW

**Comment by ercius** [comment]
it would be great to merge this in to clean up the meta data in Distiller

**Comment by swelborn** [comment]
I tested this on distiller-dev. Took an acquisition and uploaded a recent dm4 into a test folder (watched by the haadf watcher). Here is what that looks like:

image
image

The size is unknown, but I am not sure if that size is coming from another file (ser or emd?) saved alongside the dm4 in the normal directory.

**Comment by ercius** [comment]
Can you export the scan and send me the meta data? I want to see everything that is included in the Metadata listing.

**Comment by swelborn** [comment]
```json
[
  {
    "distiller_scan_id": 910,
    "detector_scan_id": 4,
    "created": "2023-06-03T07:16:25+00:00",
    "notes": null,
    "metadata": {
      "Operator": "",
      "Specimen": "",
      "Microscope": "TEAM 0.5",
      "Sample maker": "",
      "TIA rotation": "",
      "date updated": "",
      "PhysicalSizeX": 1,
      "PhysicalSizeY": 1,
      "Screen current": "",
      "Meta Data Format": "Image",
      "Meta Data Signal": "DigiScan",
      "Convergence angle": "",
      "DigiScan Rotation": 0,
      "PhysicalSizeXUnit": "",
      "PhysicalSizeYUnit": "",
      "DataBar Device Name": "DigiScan",
      "DataBar Signal Name": "Analog 0",
      "PhysicalSizeXOrigin": 0,
      "PhysicalSizeYOrigin": 0,
      "Microscope Info Name": "FEI Tecnai Remote TCPIP",
      "Microscope Info Cs(mm)": 0,
      "DataBar Exposure Number": 1159028,
      "Microscope Info Voltage": 300000,
      "DataBar Acquisition Date": "5/27/2023",
      "DataBar Acquisition Time": "7:31:56 PM",
      "DigiScan Rotation Offset": 180,
      "4Dcamera Parameters nread": 4,
      "4Dcamera Parameters nskip": 0,
      "4Dcamera Parameters stage": "124.552 162.016 -117.353 1.062 1.204130",
      "4Dcamera Parameters npause": 0,
      "4Dcamera Parameters nflyback": 300,
      "Microscope Info Imaging Mode": "DIFFRACTION",
      "Calibrations Brightness Scale": 1,
      "Calibrations Brightness Units": "",
      "DataBar Acquisition Time (OS)": 133297147164033900,
      "Calibrations Brightness Origin": 0,
      "Calibrations Dimension 1 Scale": 0.0011525608133524656,
      "Calibrations Dimension 1 Units": "µm",
      "Calibrations Dimension 2 Scale": 0.0011525608133524656,
      "Calibrations Dimension 2 Units": "µm",
      "Microscope Info Operation Mode": "SCANNING",
      "Calibrations Dimension 1 Origin": 0,
      "Calibrations Dimension 2 Origin": 0,
      "Microscope Info Probe Size (nm)": 0,
      "Microscope Info Formatted Voltage": "300kV",
      "Microscope Info Illumination Mode": "STEM",
      "Microscope Info Probe Current (nA)": 0,
      "Microscope Info STEM Camera Length": 105,
      "Calibrations DisplayCalibratedUnits": 1,
      "Microscope Info Field of View (µm)": 0.4196345943104137,
      "Microscope Info Operation Mode Type": 7,
      "Microscope Info Illumination Sub-mode": 0,
      "Microscope Info Emission Current (µA)": 0,
      "Microscope Info Stage Position Stage X": 0.00156,
      "Microscope Info Stage Position Stage Y": 0.001048,
      "Microscope Info Stage Position Stage Z": 0,
      "Microscope Info Formatted Indicated Mag": "320kx",
      "Microscope Info Indicated Magnification": 320000,
      "Microscope Info Magnification Interpolated": 0,
      "Microscope Info Stage Position Stage Alpha": 0.00048800018622661984
    }
  }
]
```

**Comment by cjh1** [comment]
@ercius Does the metadata look good, if so we can try to get this deployed.

**Comment by ercius** [comment]
This looks good as it removes all the extraneous stuff.

I have a new PR for ncempy which I wanted to deploy soon. It would include the "Session info" which could be very useful. I guess we could make that a new PR since it would require updates to the ncempy version as well.

Let deploy this as-is for now and Ill work on a new release. We can use the ncempy `getMetadata()` function in the future.

**Comment by cjh1** [comment]
Sounds good, I will get this merged and deployed.

**Review by cjh1 — APPROVED** [review]

**Comment by cjh1** [comment]
These changes are now deployed

**Pull request merged**
